apiVersion: v1
kind: ConfigMap
metadata:
  name: k8svolume-appsettings
  namespace: k8svolume
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "AllowedHosts": "*",
      "ValuesConfiguration": {
        "Message": "The configuration is working! from AKS with love from Asif" 
      } 
    }